# Generated by Django 2.2.4 on 2019-09-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeedevices',
            unique_together={('employee', 'device')},
        ),
    ]
